# Generated by Django 3.2.4 on 2022-01-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220103_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='userc',
        ),
        migrations.RemoveField(
            model_name='room',
            name='userp',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
