# Generated by Django 3.2.4 on 2022-01-08 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_alter_shipjob_job_description'),
        ('PatnerCompany', '0029_comp_drivers_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0006_user_custom_is_driver'),
        ('chat', '0005_chatgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000000000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('userc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
                ('userp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.patnercomp')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
