# Generated by Django 3.2.4 on 2022-02-17 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0029_comp_drivers_user'),
        ('chat', '0006_auto_20220108_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.comp_bids'),
        ),
    ]
