# Generated by Django 3.2.4 on 2022-01-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_referral_no_of_jobdone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission_request',
            name='Error',
        ),
        migrations.RemoveField(
            model_name='commission_request',
            name='user',
        ),
        migrations.AddField(
            model_name='commission_request',
            name='Refer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.referral'),
        ),
    ]
