# Generated by Django 3.2.4 on 2022-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20220104_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_custom',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
