# Generated by Django 3.2.4 on 2022-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_custom_is_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='commissions',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
