# Generated by Django 3.2.4 on 2021-08-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipjob',
            name='job_description',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
