# Generated by Django 3.2.4 on 2021-08-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_shipjob_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proddesc',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.shipjob'),
        ),
    ]
