# Generated by Django 3.2.4 on 2021-09-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_expired_shipjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment_Related_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer_size', models.IntegerField(default=10)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.shipjob')),
            ],
        ),
    ]
