# Generated by Django 3.2.4 on 2021-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_shipjob_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipjob',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
