# Generated by Django 3.2.4 on 2021-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_shipjob_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipjob',
            name='bid_selected',
            field=models.BooleanField(default=False),
        ),
    ]
