# Generated by Django 3.2.4 on 2021-11-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_auto_20211119_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Customer_address',
        ),
    ]
