# Generated by Django 3.2.4 on 2021-11-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_auto_20211128_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_profile',
            name='email',
        ),
    ]
