# Generated by Django 3.2.4 on 2021-11-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_remove_customer_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment_related_question',
            name='answer_size',
        ),
    ]
