# Generated by Django 3.2.4 on 2021-12-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_remove_shipment_related_question_answer_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired_shipjob',
            name='droping_Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='expired_shipjob',
            name='picking_Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shipjob',
            name='droping_Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shipjob',
            name='picking_Address',
            field=models.TextField(null=True),
        ),
    ]
