# Generated by Django 3.2.4 on 2021-12-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_auto_20211205_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proddesc',
            name='prod_box',
        ),
        migrations.RemoveField(
            model_name='proddesc',
            name='prod_in_box',
        ),
        migrations.AddField(
            model_name='proddesc',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proddesc',
            name='Weight_box',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proddesc',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proddesc',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proddesc',
            name='width',
            field=models.FloatField(),
        ),
    ]
