# Generated by Django 3.2.4 on 2021-12-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_alter_customer_profile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='company_logo',
            field=models.ImageField(blank=True, default='profile.png', upload_to='customer_logo/'),
        ),
    ]
