# Generated by Django 3.2.4 on 2021-12-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_alter_proddesc_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipjob',
            name='job_description',
            field=models.CharField(max_length=1024),
        ),
    ]
