# Generated by Django 3.2.4 on 2021-07-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('PatnerCompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comp_PresentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(max_length=1024)),
                ('co_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codrivers', to='PatnerCompany.comp_drivers')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.patnercomp')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='PatnerCompany.comp_drivers')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.shipjob')),
            ],
        ),
        migrations.CreateModel(
            name='comp_PastWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=1024)),
                ('delivered_on', models.DateTimeField(auto_now_add=True)),
                ('co_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codriver', to='PatnerCompany.comp_drivers')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.patnercomp')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='PatnerCompany.comp_drivers')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.shipjob')),
            ],
        ),
        migrations.CreateModel(
            name='comp_Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bid_amount', models.CharField(max_length=1024)),
                ('bid_on', models.DateTimeField(auto_now_add=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.patnercomp')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.shipjob')),
            ],
        ),
    ]
