# Generated by Django 3.2.4 on 2021-11-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_auto_20211119_2228'),
        ('PatnerCompany', '0002_alter_comp_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_pastwork',
            name='co_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='codriver', to='PatnerCompany.comp_drivers'),
        ),
        migrations.AlterField(
            model_name='comp_pastwork',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PatnerCompany.patnercomp'),
        ),
        migrations.AlterField(
            model_name='comp_pastwork',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to='PatnerCompany.comp_drivers'),
        ),
        migrations.AlterField(
            model_name='comp_pastwork',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Customer.shipjob'),
        ),
        migrations.AlterField(
            model_name='comp_pastwork',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transport', to='PatnerCompany.comp_transport'),
        ),
        migrations.AlterField(
            model_name='comp_presentwork',
            name='Total_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PatnerCompany.comp_bids'),
        ),
        migrations.AlterField(
            model_name='comp_presentwork',
            name='co_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='codrivers', to='PatnerCompany.comp_drivers'),
        ),
        migrations.AlterField(
            model_name='comp_presentwork',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drivers', to='PatnerCompany.comp_drivers'),
        ),
        migrations.AlterField(
            model_name='comp_presentwork',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transports', to='PatnerCompany.comp_transport'),
        ),
    ]
