# Generated by Django 3.2.4 on 2021-09-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_shipjob_is_completed'),
        ('PatnerCompany', '0002_auto_20210925_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer_candidate_jobanswer',
            new_name='shipJob_jobanswer',
        ),
    ]
