# Generated by Django 3.2.4 on 2021-11-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0004_remove_comp_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_bids',
            name='assign_driver',
            field=models.BooleanField(default=False),
        ),
    ]
