# Generated by Django 3.2.4 on 2021-11-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_remove_shipment_related_question_answer_size'),
        ('PatnerCompany', '0005_comp_bids_assign_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_bids',
            name='comp',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.patnercomp'),
        ),
        migrations.AlterField(
            model_name='comp_bids',
            name='job_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Customer.shipjob'),
        ),
    ]
