# Generated by Django 3.2.4 on 2021-11-30 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_remove_shipment_related_question_answer_size'),
        ('PatnerCompany', '0006_auto_20211201_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_pastwork',
            name='co_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codriver', to='PatnerCompany.comp_drivers'),
        ),
        migrations.AlterField(
            model_name='comp_pastwork',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.patnercomp'),
        ),
        migrations.AlterField(
            model_name='comp_pastwork',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='PatnerCompany.comp_drivers'),
        ),
        migrations.AlterField(
            model_name='comp_pastwork',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.shipjob'),
        ),
        migrations.AlterField(
            model_name='comp_pastwork',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='PatnerCompany.comp_transport'),
        ),
        migrations.AlterField(
            model_name='comp_presentwork',
            name='Total_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.comp_bids'),
        ),
        migrations.AlterField(
            model_name='comp_presentwork',
            name='co_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codrivers', to='PatnerCompany.comp_drivers'),
        ),
        migrations.AlterField(
            model_name='comp_presentwork',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='PatnerCompany.comp_drivers'),
        ),
        migrations.AlterField(
            model_name='comp_presentwork',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='PatnerCompany.comp_transport'),
        ),
    ]
