# Generated by Django 3.2.4 on 2021-12-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0007_auto_20211201_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_presentwork',
            name='ask_finalpay',
            field=models.BooleanField(default=False),
        ),
    ]
