# Generated by Django 3.2.4 on 2021-12-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0009_rename_assign_driver_comp_bids_completed_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_bids',
            name='Bid_byPartner',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='comp_bids',
            name='Bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
