# Generated by Django 3.2.4 on 2021-12-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0011_alter_comp_presentwork_payment_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.comp_presentwork')),
            ],
        ),
    ]
