# Generated by Django 3.2.4 on 2021-12-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0012_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_gone',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
