# Generated by Django 3.2.4 on 2021-12-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0014_orders_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_gone',
            new_name='order_done',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='items_json',
        ),
    ]
