# Generated by Django 3.2.4 on 2021-12-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0015_auto_20211212_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
