# Generated by Django 3.2.4 on 2021-12-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0016_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=5000, null=True)),
                ('order_done', models.CharField(max_length=5000, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatnerCompany.comp_presentwork')),
            ],
        ),
    ]
