# Generated by Django 3.2.4 on 2021-12-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0017_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_profile',
            name='company_logo',
            field=models.ImageField(blank=True, default='profile.png', upload_to='company_logo/'),
        ),
    ]
