# Generated by Django 3.2.4 on 2021-12-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0018_alter_comp_profile_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_presentwork',
            name='request_update',
            field=models.BooleanField(default=False),
        ),
    ]
