# Generated by Django 3.2.4 on 2021-12-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0020_alter_comp_pastwork_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_pastwork',
            name='Bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='comp_pastwork',
            name='Bid_byPartner',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
