# Generated by Django 3.2.4 on 2021-12-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0021_auto_20211227_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_pastwork',
            name='Rating',
            field=models.IntegerField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='comp_pastwork',
            name='co_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codriver', to='PatnerCompany.comp_drivers'),
        ),
        migrations.AlterField(
            model_name='comp_presentwork',
            name='co_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codrivers', to='PatnerCompany.comp_drivers'),
        ),
    ]
