# Generated by Django 3.2.4 on 2021-12-28 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatnerCompany', '0023_alter_comp_transport_transport_no_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_transport',
            name='transport_no_plate',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter valid Vehicle Number', regex='^[A-Z]{2}[ -][0-9]{1,2}(?: [A-Z])?(?: [A-Z]*)? [0-9]{4}$')]),
        ),
    ]
